### ISSUE TITLE
Update security white paper and FAQs with clear info on who has access to source code/device images

### ISSUE THREAD

**Issue by zwalchuk** [balena-io/docs#769]
Something like:
Device access is granted to a subset of resin.io employees to enable support and device troubleshooting.  This access is controlled by ssh key access and only after access is granted to resin.io by the device fleet manager.

Source code and device images are stored on resin.io backend servers with access limited only to administrative/operations staff and are not exposed to anyone outside of resin.io.  It is also possible to bypass the resin.io builder entirely and push only pre-built artefacts, meaning that resin.io never has access to the code at any point.

**Comment by NatasaKyvetou** [comment]
@vipulgupta2048 I just want to double-check that I am getting this right :)
The security white paper is [this one](https://www.balena.io/docs/learn/welcome/security/) so I can add the info to the device access section, right?
Also, for the FAQ [here](https://www.balena.io/docs/faq/troubleshooting/faq/) I should add a new question for access to source code/ device images as I can't see it mentioned somewhere else with a quick read through?

**Comment by vipulgupta2048** [comment]
Hey @NatasaKyvetou 

> The security white paper is this one so I can add the info to the device access section, right?

I have to confirm this one. Not sure if we term the security page as the security white paper for balena. But if it is then it indeed should be the right place for this information. The text suggested in the issue might need an update or a look as the issue was opened 3 years back.  

> Also, for the FAQ here I should add a new question for access to source code/ device images as I can't see it mentioned somewhere else with a quick read through?

It seems so. None of the existing questions seem to answer this particular question.
