### ISSUE TITLE
Document valid config.json fields

### ISSUE THREAD

**Issue by lekkas** [balena-io/docs#859]
Currently config.json configuration options are scattered in our docs, we should probably look into having a single page / manual for it

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e8m3)

**Comment by pcarranzav** [comment]
There's some documentation in https://github.com/resin-os/meta-resin#configjson - but indeed, having this centralized in the docs would be great.

**Comment by pdcastro** [comment]
Like `pcarranzav` mentioned, frequently enough I send customers (as a support agent) a URL to the `meta-balena` [Readme](https://github.com/balena-os/meta-balena#configjson) as documentation for fields in the `config.json` file, but customer feedback is that they would never have thought of looking in that place (most users may not even understand the relevance of the `meta-balena` repo).

I suggest going a bit beyond documenting the "valid fields", but also explaining for example:

* That on a device, the right file to look at is `/mnt/boot/config.json` rather than `/resin-boot/config.json`. (See also this [OS masterclass](https://gist.github.com/ZubairLK/c0f8918e983e94edc74e2e956143644d#configjson).)
  * And that the `jq` tool can be used on a host OS prompt to see the contents in a human-readable way: `jq . < /mnt/boot/config.json`.
* The recommended way of editing `config.json` -- e.g. via the web dashboard rather than manually, or using a script / tool (cc: @ZubairLK).
* Perhaps briefly mention that it's a completely different file to `config.txt`, [documented elsewhere](https://www.balena.io/docs/reference/OS/advanced/#configtxt).
* Documentation of each field, with examples of the syntax, and an example of a full file.
  * For example, the `meta-balena` Readme includes a partial example for the [sshKeys](https://github.com/balena-os/meta-balena#sshkeys) field, but it could be expanded to mention that the key could be found in the balena web dashboard, and to include an example of a key (e.g. to show that it starts with `ssh-rsa`):
```
"os": {
    "sshKeys": [
      "ssh-rsa AAAAB3Nza...M2JB paulo@macbook-pro",
      "ssh-rsa AAAAB3Nza...nFTQ paulo@zenbook"
    ]
  }
```

**Comment by samuelbacaner** [comment]
@pdcastro I'm glad I found this ticket so I could find that Readme. Can you elaborate briefly on the recommended way of editing `config.json`? Where in the web dashboard can you edit `config.json`?

**Comment by pdcastro** [comment]
@samuelbacaner, the dashboard does not exactly have an editor for `config.json`, but some of the Device Configuration settings/variables (Device Configuration tab on the web dashboard for a device) find their way to the `config.json` file on a device via the balena supervisor. I think an example is the Persistent Logging setting. Re recommended way of editing `config.json`, I am aware of the following possibilities:
* The Device Configuration tab mentioned above.
* Using the supervisor API, for example setting the hostname via [PATCH /v1/device/host-config]( https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1devicehost-config) (which may be called locally on-device from an app container even without internet access, or remotely via balenaCloud).
* Before flashing and provisioning the device, editing the file in the SD card balenaOS [resin-boot partition](https://www.balena.io/docs/reference/OS/overview/2.x/#stateless-and-read-only-rootfs).
* I heard that we have an ongoing project for a script/tool that would allow editing the file for a running device. Maybe @ZubairLK can confirm or deny this rumour? :-)

**Comment by samuelbacaner** [comment]
Thanks, @pdcastro. In my case, I needed to add a custom udev rule. I ended up adding it using @ZubairLK's guidance [here](https://gist.github.com/ZubairLK/c0f8918e983e94edc74e2e956143644d#advanced-editing-configjson-by-hand). When I set up more devices in the future, I'll probably edit the config file before flashing.

**Comment by garethtdavies** [comment]
Closing this via #1249
